language: python

python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
install:
  - pip install -U -q -r requirements.txt

sudo: false

# command to run tests
script:
  - python tests/test.py

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2719e03e49a0e4948342  # for gitter
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

branches:
  only:
  - master

after_success:
  - bash <(curl -s https://codecov.io/bash)